apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-service-dev

resources:
  - namespace.yaml
  - ../../base

namePrefix: dev-

labels:
  - pairs:
      environment: dev

patches:
  - path: replica-patch.yaml
    target:
      kind: Deployment
      name: web-service

images:
  - name: us-central1-docker.pkg.dev/ops-master-project/app-services-repo-production/web-service
    newName: us-central1-docker.pkg.dev/ops-master-project/app-services-repo-dev/web-service
    newTag: dev-latest

configMapGenerator:
  - name: web-service-config
    behavior: merge
    literals:
      - APP_ENV=development
      - LOG_LEVEL=debug
      - CACHE_TTL_SECONDS=60
