apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  labels:
    app: web-service
    app.kubernetes.io/name: web-service
    app.kubernetes.io/part-of: ops-master-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: web-service
        app.kubernetes.io/name: web-service
    spec:
      imagePullSecrets:
        - name: gar-reader-secret
      containers:
        - name: web-service
          image: us-central1-docker.pkg.dev/ops-master-project/app-services-repo-production/web-service:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: web-service-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /healthz/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5
