apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web-service
    app.kubernetes.io/name: web-service
    app.kubernetes.io/part-of: ops-master-pipeline
spec:
  selector:
    app: web-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
