apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-service-prod

resources:
  - namespace.yaml
  - ../../base

namePrefix: prod-

labels:
  - pairs:
      environment: prod

patches:
  - path: replica-patch.yaml
    target:
      kind: Deployment
      name: web-service

images:
  - name: us-central1-docker.pkg.dev/ops-master-project/app-services-repo-production/web-service
    newTag: v1.0.0

configMapGenerator:
  - name: web-service-config
    behavior: merge
    literals:
      - APP_ENV=production
      - LOG_LEVEL=warn
      - CACHE_TTL_SECONDS=600
