apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
  namespace: argocd
  labels:
    environment: dev
    app.kubernetes.io/part-of: ops-master-pipeline
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/kushalsk99/ops-master-pipeline-argo-gitops.git
    targetRevision: HEAD
    path: kubernetes/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: web-service-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
