apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
  labels:
    app.kubernetes.io/name: root-application
    app.kubernetes.io/part-of: ops-master-pipeline
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/kushalsk99/ops-master-pipeline-argo-gitops.git
    targetRevision: HEAD
    path: argocd
    directory:
      recurse: false
      exclude: "{root-application.yaml}"

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
